################################################################################
# Generated using Joshua T. Fisher's 'CMake Builder'.
# Link: https://github.com/playmer/CmakeBuilder 
################################################################################
target_sources(Sound
  PRIVATE
    ${CMAKE_CURRENT_LIST_DIR}/AttenuatorNode.cpp
    ${CMAKE_CURRENT_LIST_DIR}/AttenuatorNode.hpp
    ${CMAKE_CURRENT_LIST_DIR}/AudioIOInterface.cpp
    ${CMAKE_CURRENT_LIST_DIR}/AudioIOInterface.hpp
    ${CMAKE_CURRENT_LIST_DIR}/AudioMixer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/AudioMixer.hpp
    ${CMAKE_CURRENT_LIST_DIR}/CustomAudioNode.cpp
    ${CMAKE_CURRENT_LIST_DIR}/CustomAudioNode.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Definitions.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Definitions.hpp
    ${CMAKE_CURRENT_LIST_DIR}/DspFilterNodes.cpp
    ${CMAKE_CURRENT_LIST_DIR}/DspFilterNodes.hpp
    ${CMAKE_CURRENT_LIST_DIR}/EmitterNode.cpp
    ${CMAKE_CURRENT_LIST_DIR}/EmitterNode.hpp
    ${CMAKE_CURRENT_LIST_DIR}/FileDecoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/FileDecoder.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Filters.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Filters.hpp
    ${CMAKE_CURRENT_LIST_DIR}/GeneratedAudio.cpp
    ${CMAKE_CURRENT_LIST_DIR}/GeneratedAudio.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Interpolator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Interpolator.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ListenerNode.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ListenerNode.hpp
    ${CMAKE_CURRENT_LIST_DIR}/LockFreeQueue.hpp
    ${CMAKE_CURRENT_LIST_DIR}/PitchChange.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PitchChange.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Precompiled.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Precompiled.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Recording.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Recording.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Resampler.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Resampler.hpp
    ${CMAKE_CURRENT_LIST_DIR}/RingBuffer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RingBuffer.hpp
    ${CMAKE_CURRENT_LIST_DIR}/SimpleSound.cpp
    ${CMAKE_CURRENT_LIST_DIR}/SimpleSound.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Sound.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Sound.hpp
    ${CMAKE_CURRENT_LIST_DIR}/SoundAsset.cpp
    ${CMAKE_CURRENT_LIST_DIR}/SoundAsset.hpp
    ${CMAKE_CURRENT_LIST_DIR}/SoundAttenuator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/SoundAttenuator.hpp
    ${CMAKE_CURRENT_LIST_DIR}/SoundCue.cpp
    ${CMAKE_CURRENT_LIST_DIR}/SoundCue.hpp
    ${CMAKE_CURRENT_LIST_DIR}/SoundEmitter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/SoundEmitter.hpp
    ${CMAKE_CURRENT_LIST_DIR}/SoundInstance.cpp
    ${CMAKE_CURRENT_LIST_DIR}/SoundInstance.hpp
    ${CMAKE_CURRENT_LIST_DIR}/SoundListener.cpp
    ${CMAKE_CURRENT_LIST_DIR}/SoundListener.hpp
    ${CMAKE_CURRENT_LIST_DIR}/SoundNode.cpp
    ${CMAKE_CURRENT_LIST_DIR}/SoundNode.hpp
    ${CMAKE_CURRENT_LIST_DIR}/SoundNodeGraph.cpp
    ${CMAKE_CURRENT_LIST_DIR}/SoundNodeGraph.hpp
    ${CMAKE_CURRENT_LIST_DIR}/SoundSpace.cpp
    ${CMAKE_CURRENT_LIST_DIR}/SoundSpace.hpp
    ${CMAKE_CURRENT_LIST_DIR}/SoundStandard.cpp
    ${CMAKE_CURRENT_LIST_DIR}/SoundStandard.hpp
    ${CMAKE_CURRENT_LIST_DIR}/SoundSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/SoundSystem.hpp
    ${CMAKE_CURRENT_LIST_DIR}/SoundTag.cpp
    ${CMAKE_CURRENT_LIST_DIR}/SoundTag.hpp
    ${CMAKE_CURRENT_LIST_DIR}/VBAP.cpp
    ${CMAKE_CURRENT_LIST_DIR}/VBAP.hpp
    ${CMAKE_CURRENT_LIST_DIR}/VolumeModifier.cpp
    ${CMAKE_CURRENT_LIST_DIR}/VolumeModifier.hpp
)
