################################################################################
# Generated using Joshua T. Fisher's 'CMake Builder'.
# Link: https://github.com/playmer/CmakeBuilder 
################################################################################
target_sources(Zilch
  PRIVATE
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Any.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Any.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/ArrayClass.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/ArrayClass.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Base64.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Base64.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Binding.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Binding.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/CodeGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/CodeGenerator.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/CodeLocation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/CodeLocation.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Color.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Color.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/CompilationErrors.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/CompilationErrors.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Composition.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Composition.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/ConsoleClass.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/ConsoleClass.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/ConstructorBinding.inl
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Core.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Core.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/DataDrivenLexer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/DataDrivenLexer.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/DataDrivenLexer.inl
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Debugging.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Debugging.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Delegate.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Delegate.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/DestructibleBuffer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/DestructibleBuffer.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Documentation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Documentation.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/ErrorDatabase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/ErrorDatabase.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Events.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Events.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/ExecutableState.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/ExecutableState.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/FilePathClass.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/FilePathClass.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/FileStreamClass.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/FileStreamClass.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Formatter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Formatter.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/ForwardDeclarations.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Function.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Function.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/General.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/GrammarConstants.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/GrammarConstants.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Handle.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Handle.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/HandleManager.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/HandleManager.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/HashContainer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/HashContainer.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/InstructionsEnum.inl
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Json.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Json.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Library.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Library.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/LocalBuild.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Matrix.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Matrix.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Members.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Members.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/MethodBinding.inl
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/MultiPrimitive.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/MultiPrimitive.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Opcode.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Opcode.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/OverloadResolver.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/OverloadResolver.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Parser.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Parser.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Plugin.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Plugin.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/ProcessClass.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/ProcessClass.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Project.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Project.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/RandomClass.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/RandomClass.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Range.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/RangeBinding.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Setup.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Setup.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Sha1.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Sha1.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Shared.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Shared.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/SharedReference.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/StaticLibrary.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/StaticLibrary.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/StreamInterface.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/StreamInterface.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/StringBuilderClass.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/StringBuilderClass.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/StringConstants.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/StringConstants.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/StubCode.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/StubCode.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Syntaxer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Syntaxer.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/SyntaxTree.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/SyntaxTree.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/SyntaxTreeHelpers.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/SyntaxTreeHelpers.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/TemplateBinding.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/TemplateBinding.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Timer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Timer.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Token.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Tokenizer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Tokenizer.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/TokenReader.inl
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Traits.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Traits.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Type.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Type.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/UntypedBlockArray.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/VirtualMachine.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/VirtualMachine.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/VirtualMethodBinding.inl
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/VirtualTableBinding.inl
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/WebSocket.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/WebSocket.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Wrapper.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Wrapper.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Zilch.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project/Zilch/Zilch.hpp
)
