################################################################################
# Generated using Joshua T. Fisher's 'CMake Builder'.
# Link: https://github.com/playmer/CmakeBuilder 
################################################################################
target_sources(Math
  PRIVATE
    ${CMAKE_CURRENT_LIST_DIR}/BlockVector3.cpp
    ${CMAKE_CURRENT_LIST_DIR}/BoolVector2.cpp
    ${CMAKE_CURRENT_LIST_DIR}/BoolVector3.cpp
    ${CMAKE_CURRENT_LIST_DIR}/BoolVector4.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Curve.cpp
    ${CMAKE_CURRENT_LIST_DIR}/DecomposedMatrix4.cpp
    ${CMAKE_CURRENT_LIST_DIR}/EulerAngles.cpp
    ${CMAKE_CURRENT_LIST_DIR}/EulerOrder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ExtendableMath.cpp
    ${CMAKE_CURRENT_LIST_DIR}/IntVector2.cpp
    ${CMAKE_CURRENT_LIST_DIR}/IntVector3.cpp
    ${CMAKE_CURRENT_LIST_DIR}/IntVector4.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Math.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Matrix2.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Matrix3.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Matrix4.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Numerical.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Precompiled.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Quaternion.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Random.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Reals.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ToString.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Vector2.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Vector3.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Vector4.cpp
#  PUBLIC
    ${CMAKE_CURRENT_LIST_DIR}/BasicNativeTypesMath.inl
    ${CMAKE_CURRENT_LIST_DIR}/BlockVector3.hpp
    ${CMAKE_CURRENT_LIST_DIR}/BoolVector2.hpp
    ${CMAKE_CURRENT_LIST_DIR}/BoolVector3.hpp
    ${CMAKE_CURRENT_LIST_DIR}/BoolVector4.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ByteColor.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ColorDefinitions.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ConjugateGradient.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Curve.hpp
    ${CMAKE_CURRENT_LIST_DIR}/DecomposedMatrix4.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ErrorCallbacks.hpp
    ${CMAKE_CURRENT_LIST_DIR}/EulerAngles.hpp
    ${CMAKE_CURRENT_LIST_DIR}/EulerOrder.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ExtendableMath.hpp
    ${CMAKE_CURRENT_LIST_DIR}/GaussSeidelSolver.hpp
    ${CMAKE_CURRENT_LIST_DIR}/GenericVector.hpp
    ${CMAKE_CURRENT_LIST_DIR}/GenericVector.inl
    ${CMAKE_CURRENT_LIST_DIR}/IndexPolicies.hpp
    ${CMAKE_CURRENT_LIST_DIR}/IntVector2.hpp
    ${CMAKE_CURRENT_LIST_DIR}/IntVector3.hpp
    ${CMAKE_CURRENT_LIST_DIR}/IntVector4.hpp
    ${CMAKE_CURRENT_LIST_DIR}/JacobiSolver.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Math.hpp
    ${CMAKE_CURRENT_LIST_DIR}/MathImports.hpp
    ${CMAKE_CURRENT_LIST_DIR}/MathStandard.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Matrix2.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Matrix3.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Matrix4.hpp
    ${CMAKE_CURRENT_LIST_DIR}/MatrixStorage.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Numerical.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Precompiled.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Quaternion.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Random.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Reals.hpp
    ${CMAKE_CURRENT_LIST_DIR}/SharedVectorFunctions.hpp
    ${CMAKE_CURRENT_LIST_DIR}/SimConversion.hpp
    ${CMAKE_CURRENT_LIST_DIR}/SimMath.hpp
    ${CMAKE_CURRENT_LIST_DIR}/SimMatrix3.hpp
    ${CMAKE_CURRENT_LIST_DIR}/SimMatrix3.inl
    ${CMAKE_CURRENT_LIST_DIR}/SimMatrix4.hpp
    ${CMAKE_CURRENT_LIST_DIR}/SimMatrix4.inl
    ${CMAKE_CURRENT_LIST_DIR}/SimpleCgPolicies.hpp
    ${CMAKE_CURRENT_LIST_DIR}/SimVectors.hpp
    ${CMAKE_CURRENT_LIST_DIR}/SimVectors.inl
    ${CMAKE_CURRENT_LIST_DIR}/SimVectorSpecific.inl
    ${CMAKE_CURRENT_LIST_DIR}/ToString.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Vector2.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Vector3.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Vector3.inl
    ${CMAKE_CURRENT_LIST_DIR}/Vector4.hpp
    ${CMAKE_CURRENT_LIST_DIR}/VectorHashPolicy.hpp
    ${CMAKE_CURRENT_LIST_DIR}/WeightedProbabilityTable.hpp
)
