################################################################################
# Generated using Joshua T. Fisher's 'CMake Builder'.
# Link: https://github.com/playmer/CmakeBuilder 
################################################################################
target_sources(GeometryProcessor
  PRIVATE
    ${CMAKE_CURRENT_LIST_DIR}/AnimationProcessor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/AnimationProcessor.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ArchetypeProcessor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ArchetypeProcessor.hpp
    ${CMAKE_CURRENT_LIST_DIR}/GeometryImporter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/GeometryImporter.hpp
    ${CMAKE_CURRENT_LIST_DIR}/GeometryProcessorDataStructures.hpp
    ${CMAKE_CURRENT_LIST_DIR}/GeometryUtility.cpp
    ${CMAKE_CURRENT_LIST_DIR}/GeometryUtility.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Main.cpp
    ${CMAKE_CURRENT_LIST_DIR}/MeshProcessor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/MeshProcessor.hpp
    ${CMAKE_CURRENT_LIST_DIR}/PhysicsMeshProcessor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PhysicsMeshProcessor.hpp
    ${CMAKE_CURRENT_LIST_DIR}/PivotProcessor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PivotProcessor.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Precompiled.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Precompiled.hpp
    ${CMAKE_CURRENT_LIST_DIR}/SkeletonProcessor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/SkeletonProcessor.hpp
    ${CMAKE_CURRENT_LIST_DIR}/TextureProcessor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/TextureProcessor.hpp
    ${CMAKE_CURRENT_LIST_DIR}/VertexDescriptionBuilder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/VertexDescriptionBuilder.hpp
)
