################################################################################
# Generated using Joshua T. Fisher's 'CMake Builder'.
# Link: https://github.com/playmer/CmakeBuilder 
################################################################################
target_sources(Engine
  PRIVATE
    ${CMAKE_CURRENT_LIST_DIR}/Animation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Animation.hpp
    ${CMAKE_CURRENT_LIST_DIR}/AnimationGraph.cpp
    ${CMAKE_CURRENT_LIST_DIR}/AnimationGraph.hpp
    ${CMAKE_CURRENT_LIST_DIR}/AnimationGraphEvents.cpp
    ${CMAKE_CURRENT_LIST_DIR}/AnimationGraphEvents.hpp
    ${CMAKE_CURRENT_LIST_DIR}/AnimationNode.cpp
    ${CMAKE_CURRENT_LIST_DIR}/AnimationNode.hpp
    ${CMAKE_CURRENT_LIST_DIR}/AnimationNode.inl
    ${CMAKE_CURRENT_LIST_DIR}/Archetype.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Archetype.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ArchetypeRebuilder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ArchetypeRebuilder.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Area.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Area.hpp
    ${CMAKE_CURRENT_LIST_DIR}/AsyncProcess.cpp
    ${CMAKE_CURRENT_LIST_DIR}/AsyncProcess.hpp
    ${CMAKE_CURRENT_LIST_DIR}/BasicActions.cpp
    ${CMAKE_CURRENT_LIST_DIR}/BuildVersion.cpp
    ${CMAKE_CURRENT_LIST_DIR}/BuildVersion.hpp
    ${CMAKE_CURRENT_LIST_DIR}/BuildVersion.inl
    ${CMAKE_CURRENT_LIST_DIR}/Cog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Cog.hpp
    ${CMAKE_CURRENT_LIST_DIR}/CogHelpers.cpp
    ${CMAKE_CURRENT_LIST_DIR}/CogHelpers.hpp
    ${CMAKE_CURRENT_LIST_DIR}/CogId.cpp
    ${CMAKE_CURRENT_LIST_DIR}/CogId.hpp
    ${CMAKE_CURRENT_LIST_DIR}/CogInitializer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/CogInitializer.hpp
    ${CMAKE_CURRENT_LIST_DIR}/CogMeta.cpp
    ${CMAKE_CURRENT_LIST_DIR}/CogMeta.hpp
    ${CMAKE_CURRENT_LIST_DIR}/CogMetaComposition.cpp
    ${CMAKE_CURRENT_LIST_DIR}/CogMetaComposition.hpp
    ${CMAKE_CURRENT_LIST_DIR}/CogOperations.cpp
    ${CMAKE_CURRENT_LIST_DIR}/CogOperations.hpp
    ${CMAKE_CURRENT_LIST_DIR}/CogPath.cpp
    ${CMAKE_CURRENT_LIST_DIR}/CogPath.hpp
    ${CMAKE_CURRENT_LIST_DIR}/CogRange.cpp
    ${CMAKE_CURRENT_LIST_DIR}/CogRange.hpp
    ${CMAKE_CURRENT_LIST_DIR}/CogRestoreState.cpp
    ${CMAKE_CURRENT_LIST_DIR}/CogRestoreState.hpp
    ${CMAKE_CURRENT_LIST_DIR}/CogSelection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/CogSelection.hpp
    ${CMAKE_CURRENT_LIST_DIR}/CogSerialization.cpp
    ${CMAKE_CURRENT_LIST_DIR}/CogSerialization.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ColorGradient.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ColorGradient.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Component.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Component.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ComponentHierarchy.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ComponentMeta.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ComponentMeta.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Configuration.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Configuration.hpp
    ${CMAKE_CURRENT_LIST_DIR}/DataSource.cpp
    ${CMAKE_CURRENT_LIST_DIR}/DataSource.hpp
    ${CMAKE_CURRENT_LIST_DIR}/DebugDraw.cpp
    ${CMAKE_CURRENT_LIST_DIR}/DebugDraw.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Documentation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Documentation.hpp
    ${CMAKE_CURRENT_LIST_DIR}/DocumentResource.cpp
    ${CMAKE_CURRENT_LIST_DIR}/DocumentResource.hpp
    ${CMAKE_CURRENT_LIST_DIR}/EditorSettings.cpp
    ${CMAKE_CURRENT_LIST_DIR}/EditorSettings.hpp
    ${CMAKE_CURRENT_LIST_DIR}/EditorSupport.cpp
    ${CMAKE_CURRENT_LIST_DIR}/EditorSupport.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Engine.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Engine.hpp
    ${CMAKE_CURRENT_LIST_DIR}/EngineBindingExtensions.cpp
    ${CMAKE_CURRENT_LIST_DIR}/EngineBindingExtensions.hpp
    ${CMAKE_CURRENT_LIST_DIR}/EngineContainers.hpp
    ${CMAKE_CURRENT_LIST_DIR}/EngineEvents.cpp
    ${CMAKE_CURRENT_LIST_DIR}/EngineEvents.hpp
    ${CMAKE_CURRENT_LIST_DIR}/EngineLibraryExtensions.cpp
    ${CMAKE_CURRENT_LIST_DIR}/EngineLibraryExtensions.hpp
    ${CMAKE_CURRENT_LIST_DIR}/EngineMath.hpp
    ${CMAKE_CURRENT_LIST_DIR}/EngineObject.cpp
    ${CMAKE_CURRENT_LIST_DIR}/EngineObject.hpp
    ${CMAKE_CURRENT_LIST_DIR}/EngineStandard.cpp
    ${CMAKE_CURRENT_LIST_DIR}/EngineStandard.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Environment.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Environment.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ErrorContext.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ErrorContext.hpp
    ${CMAKE_CURRENT_LIST_DIR}/EventDirectoryWatcher.cpp
    ${CMAKE_CURRENT_LIST_DIR}/EventDirectoryWatcher.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Factory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Factory.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Game.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Game.hpp
    ${CMAKE_CURRENT_LIST_DIR}/GamePadSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/GamePadSystem.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Gradient.hpp
    ${CMAKE_CURRENT_LIST_DIR}/HeightMap.cpp
    ${CMAKE_CURRENT_LIST_DIR}/HeightMap.hpp
    ${CMAKE_CURRENT_LIST_DIR}/HeightMapSource.cpp
    ${CMAKE_CURRENT_LIST_DIR}/HeightMapSource.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Hierarchy.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Hierarchy.hpp
    ${CMAKE_CURRENT_LIST_DIR}/HierarchyRange.cpp
    ${CMAKE_CURRENT_LIST_DIR}/HierarchyRange.hpp
    ${CMAKE_CURRENT_LIST_DIR}/HierarchySpline.cpp
    ${CMAKE_CURRENT_LIST_DIR}/HierarchySpline.hpp
    ${CMAKE_CURRENT_LIST_DIR}/JobSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/JobSystem.hpp
    ${CMAKE_CURRENT_LIST_DIR}/JoystickSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/JoystickSystem.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Keyboard.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Keyboard.hpp
    ${CMAKE_CURRENT_LIST_DIR}/LauncherConfiguration.cpp
    ${CMAKE_CURRENT_LIST_DIR}/LauncherConfiguration.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Level.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Level.hpp
    ${CMAKE_CURRENT_LIST_DIR}/MetaOperations.cpp
    ${CMAKE_CURRENT_LIST_DIR}/MetaOperations.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Mouse.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Mouse.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Noise.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Noise.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ObjectLink.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ObjectLink.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ObjectLoader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ObjectLoader.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ObjectSaver.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ObjectSaver.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ObjectStore.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ObjectStore.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Operation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Operation.hpp
    ${CMAKE_CURRENT_LIST_DIR}/OsShell.cpp
    ${CMAKE_CURRENT_LIST_DIR}/OsShell.hpp
    ${CMAKE_CURRENT_LIST_DIR}/OsWindow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/OsWindow.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Precompiled.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Precompiled.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Project.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Project.hpp
    ${CMAKE_CURRENT_LIST_DIR}/PropertyTrack.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PropertyTrack.hpp
    ${CMAKE_CURRENT_LIST_DIR}/PropertyTrack.inl
    ${CMAKE_CURRENT_LIST_DIR}/ProxyObject.hpp
    ${CMAKE_CURRENT_LIST_DIR}/RaycastProvider.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RaycastProvider.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Rectangle.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Rectangle.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Resource.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Resource.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ResourceLibrary.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ResourceLibrary.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ResourceManager.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ResourceManager.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ResourcePropertyOperations.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ResourcePropertyOperations.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ResourceSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ResourceSystem.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ResourceTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ResourceTable.hpp
    ${CMAKE_CURRENT_LIST_DIR}/SampleCurve.cpp
    ${CMAKE_CURRENT_LIST_DIR}/SampleCurve.hpp
    ${CMAKE_CURRENT_LIST_DIR}/SceneGraph.cpp
    ${CMAKE_CURRENT_LIST_DIR}/SceneGraph.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ScriptDebugEngine.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ScriptDebugEngine.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ShortcutsDoc.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ShortcutsDoc.hpp
    ${CMAKE_CURRENT_LIST_DIR}/SimpleResourceFactory.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Space.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Space.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Spline.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Spline.hpp
    ${CMAKE_CURRENT_LIST_DIR}/System.cpp
    ${CMAKE_CURRENT_LIST_DIR}/System.hpp
    ${CMAKE_CURRENT_LIST_DIR}/SystemObjectManager.cpp
    ${CMAKE_CURRENT_LIST_DIR}/SystemObjectManager.hpp
    ${CMAKE_CURRENT_LIST_DIR}/TextResource.cpp
    ${CMAKE_CURRENT_LIST_DIR}/TextResource.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ThreadDispatch.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ThreadDispatch.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Time.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Time.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Tracker.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tracker.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Transform.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Transform.hpp
    ${CMAKE_CURRENT_LIST_DIR}/TransformSupport.cpp
    ${CMAKE_CURRENT_LIST_DIR}/TransformSupport.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Tweakables.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Tweakables.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Tweakables.inl
    ${CMAKE_CURRENT_LIST_DIR}/ZilchAction.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ZilchAction.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ZilchManager.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ZilchManager.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ZilchResource.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ZilchResource.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Action/Action.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Action/Action.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Action/ActionEase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Action/ActionEase.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Action/ActionGenerator.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Action/ActionSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Action/ActionSystem.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Action/BasicActions.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Action/MetaAction.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Action/MetaAction.hpp
)
