################################################################################
# Generated using Joshua T. Fisher's 'CMake Builder'.
# Link: https://github.com/playmer/CmakeBuilder 
################################################################################
target_sources(Platform
  PRIVATE
    ${CMAKE_CURRENT_LIST_DIR}/File.cpp
    ${CMAKE_CURRENT_LIST_DIR}/FileEvents.cpp
    ${CMAKE_CURRENT_LIST_DIR}/FilePath.cpp
    ${CMAKE_CURRENT_LIST_DIR}/FileSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/IpAddress.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Precompiled.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Process.cpp
    ${CMAKE_CURRENT_LIST_DIR}/UnicodeUtility.cpp
#  PUBLIC
    ${CMAKE_CURRENT_LIST_DIR}/CommandLineSupport.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ConsoleListeners.hpp
    ${CMAKE_CURRENT_LIST_DIR}/CrashHandler.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Debug.hpp
    ${CMAKE_CURRENT_LIST_DIR}/DebugSymbolInformation.hpp
    ${CMAKE_CURRENT_LIST_DIR}/DirectoryWatcher.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ExternalLibrary.hpp
    ${CMAKE_CURRENT_LIST_DIR}/File.hpp
    ${CMAKE_CURRENT_LIST_DIR}/FileEvents.hpp
    ${CMAKE_CURRENT_LIST_DIR}/FilePath.hpp
    ${CMAKE_CURRENT_LIST_DIR}/FileSystem.hpp
    ${CMAKE_CURRENT_LIST_DIR}/FpControl.hpp
    ${CMAKE_CURRENT_LIST_DIR}/IpAddress.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lock.hpp
    ${CMAKE_CURRENT_LIST_DIR}/OsHandle.hpp
    ${CMAKE_CURRENT_LIST_DIR}/PlatformSelector.hpp
    ${CMAKE_CURRENT_LIST_DIR}/PlatformStandard.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Precompiled.hpp
    ${CMAKE_CURRENT_LIST_DIR}/PrivateImplementation.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Process.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Registry.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Resolution.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Socket.hpp
    ${CMAKE_CURRENT_LIST_DIR}/SocketConstants.hpp
    ${CMAKE_CURRENT_LIST_DIR}/SocketEnums.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Thread.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ThreadSync.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Timer.hpp
    ${CMAKE_CURRENT_LIST_DIR}/TimerBlock.hpp
    ${CMAKE_CURRENT_LIST_DIR}/UnicodeUtility.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Utilities.hpp
)
