################################################################################
# Generated using Joshua T. Fisher's 'CMake Builder'.
# Link: https://github.com/playmer/CmakeBuilder 
################################################################################
target_sources(Project
  PRIVATE
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Any.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Any.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/ArrayClass.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/ArrayClass.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Base64.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Base64.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Binding.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Binding.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/CodeGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/CodeGenerator.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/CodeLocation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/CodeLocation.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Color.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Color.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/CompilationErrors.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/CompilationErrors.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Composition.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Composition.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/ConsoleClass.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/ConsoleClass.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/ConstructorBinding.inl
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Core.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Core.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/DataDrivenLexer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/DataDrivenLexer.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/DataDrivenLexer.inl
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Debugging.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Debugging.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Delegate.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Delegate.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/DestructibleBuffer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/DestructibleBuffer.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Events.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Events.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/ExecutableState.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/ExecutableState.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/FilePathClass.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/FilePathClass.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/FileStreamClass.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/FileStreamClass.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Formatter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Formatter.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/ForwardDeclarations.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Function.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Function.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/General.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/GrammarConstants.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/GrammarConstants.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Handle.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Handle.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/HandleManager.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/HandleManager.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/HashContainer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/HashContainer.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/InstructionsEnum.inl
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Json.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Json.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Library.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Library.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/LocalBuild.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Matrix.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Matrix.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Members.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Members.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/MethodBinding.inl
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/MultiPrimitive.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/MultiPrimitive.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Opcode.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Opcode.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/OverloadResolver.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/OverloadResolver.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Parser.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Parser.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Plugin.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Plugin.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/ProcessClass.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/ProcessClass.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Project.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Project.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/RandomClass.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/RandomClass.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Range.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/RangeBinding.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Setup.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Setup.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Sha1.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Sha1.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Shared.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Shared.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/SharedReference.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/StaticLibrary.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/StaticLibrary.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/StreamInterface.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/StreamInterface.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/StringBuilderClass.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/StringBuilderClass.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/StringConstants.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/StringConstants.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/StubCode.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/StubCode.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Syntaxer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Syntaxer.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/SyntaxTree.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/SyntaxTree.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/SyntaxTreeHelpers.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/SyntaxTreeHelpers.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/TemplateBinding.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/TemplateBinding.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Timer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Timer.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Token.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Tokenizer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Tokenizer.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/TokenReader.inl
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Traits.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Traits.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Type.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Type.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/UntypedBlockArray.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/VirtualMachine.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/VirtualMachine.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/VirtualMethodBinding.inl
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/VirtualTableBinding.inl
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/WebSocket.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/WebSocket.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Wrapper.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Wrapper.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Zilch.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Zilch/Zilch.hpp
)
