################################################################################
# Generated using Joshua T. Fisher's 'CMake Builder'.
# Link: https://github.com/playmer/CmakeBuilder 
################################################################################
target_sources(Common
  PRIVATE
    ${CMAKE_CURRENT_LIST_DIR}/CommonStandard.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Guid.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Precompiled.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Time.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Containers/BitStream.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Containers/ByteBuffer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Diagnostic/Console.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Diagnostic/Diagnostic.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lexer/Lexer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Memory/Block.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Memory/Graph.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Memory/Heap.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Memory/Pool.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Memory/Stack.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Regex/Regex.cpp
    #${CMAKE_CURRENT_LIST_DIR}/Regex/RegexNo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/String/CharacterTraits.cpp
    ${CMAKE_CURRENT_LIST_DIR}/String/Rune.cpp
    ${CMAKE_CURRENT_LIST_DIR}/String/String.cpp
    ${CMAKE_CURRENT_LIST_DIR}/String/StringBuilder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/String/StringConversion.cpp
    ${CMAKE_CURRENT_LIST_DIR}/String/StringRange.cpp
    ${CMAKE_CURRENT_LIST_DIR}/String/StringUtility.cpp
    ${CMAKE_CURRENT_LIST_DIR}/String/ToString.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Utility/Atomic.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Utility/Callback.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Utility/Determinism.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Utility/Functor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Utility/HalfFloat.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Utility/Misc.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Utility/SpinLock.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Utility/Status.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Utility/Variant.cpp
#  PUBLIC
    ${CMAKE_CURRENT_LIST_DIR}/CommonForwardDeclarations.hpp
    ${CMAKE_CURRENT_LIST_DIR}/CommonStandard.hpp
    ${CMAKE_CURRENT_LIST_DIR}/NullPtr.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Precompiled.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Singleton.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Time.hpp
    ${CMAKE_CURRENT_LIST_DIR}/VirtualAny.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Containers/Algorithm.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Containers/Allocator.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Containers/Array.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Containers/ArrayMap.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Containers/ArraySet.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Containers/BitStream.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Containers/BitStream.inl
    ${CMAKE_CURRENT_LIST_DIR}/Containers/BlockArray.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Containers/ByteBuffer.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Containers/ContainerCommon.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Containers/CyclicArray.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Containers/HashedContainer.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Containers/Hashing.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Containers/HashMap.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Containers/HashSet.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Containers/InList.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Containers/OrderedHashMap.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Containers/OrderedHashSet.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Containers/OwnedArray.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Containers/Precompiled.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Containers/SlotMap.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Containers/SortedArray.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Containers/TypeTraits.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Containers/UnsortedMap.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Diagnostic/Console.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Diagnostic/Diagnostic.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lexer/Lexer.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lexer/Lexer.inl
    ${CMAKE_CURRENT_LIST_DIR}/Memory/Block.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Memory/Graph.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Memory/Heap.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Memory/LocalStackAllocator.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Memory/Memory.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Memory/Pool.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Memory/Precompiled.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Memory/Stack.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Memory/ZeroAllocator.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Regex/Regex.hpp
    ${CMAKE_CURRENT_LIST_DIR}/StlBinding/Array.hpp
    ${CMAKE_CURRENT_LIST_DIR}/StlBinding/Associative.hpp
    ${CMAKE_CURRENT_LIST_DIR}/StlBinding/String.hpp
    ${CMAKE_CURRENT_LIST_DIR}/String/CharacterTraits.hpp
    ${CMAKE_CURRENT_LIST_DIR}/String/FixedString.hpp
    ${CMAKE_CURRENT_LIST_DIR}/String/Precompiled.hpp
    ${CMAKE_CURRENT_LIST_DIR}/String/Rune.hpp
    ${CMAKE_CURRENT_LIST_DIR}/String/String.hpp
    ${CMAKE_CURRENT_LIST_DIR}/String/StringBuilder.hpp
    ${CMAKE_CURRENT_LIST_DIR}/String/StringConversion.hpp
    ${CMAKE_CURRENT_LIST_DIR}/String/StringRange.hpp
    ${CMAKE_CURRENT_LIST_DIR}/String/StringUtility.hpp
    ${CMAKE_CURRENT_LIST_DIR}/String/ToString.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Utility/Atomic.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Utility/BasicNativeTypes.inl
    ${CMAKE_CURRENT_LIST_DIR}/Utility/BitField.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Utility/BitMath.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Utility/BitTypes.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Utility/ByteEnum.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Utility/Callback.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Utility/ConditionalRange.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Utility/Determinism.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Utility/EnumDeclaration.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Utility/ForEachRange.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Utility/Functor.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Utility/Guid.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Utility/HalfFloat.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Utility/IdSequence.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Utility/IdStore.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Utility/ItemCache.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Utility/Log2.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Utility/MaxSizeof.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Utility/Misc.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Utility/NativeType.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Utility/PointerCast.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Utility/SpinLock.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Utility/Standard.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Utility/Status.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Utility/TextStream.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Utility/Typedefs.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Utility/uintN.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Utility/UniquePointer.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Utility/Variant.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Utility/Variant.inl
    ${CMAKE_CURRENT_LIST_DIR}/Utility/VariantConfig.hpp
)
