#pragma once

#include <limits.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>
#include <sys/types.h>

#if defined(__cplusplus)
#include <cstring>
#include <list>
#include <map>
#include <math.h>
#include <memory>
#include <new>
#include <set>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

#include "Repo/include/assimp/Compiler/pushpack1.h"
#include "Repo/include/assimp/Compiler/poppack1.h"
#include "Repo/include/assimp/Compiler/pstdint.h"
// Includes
#include "Repo/include/assimp/anim.h"
#include "Repo/include/assimp/ai_assert.h"
#include "Repo/include/assimp/camera.h"
#include "Repo/include/assimp/color4.h"
#include "Repo/include/assimp/config.h"
#include "Repo/include/assimp/defs.h"
#include "Repo/include/assimp/cfileio.h"
#include "Repo/include/assimp/light.h"
#include "Repo/include/assimp/material.h"
#include "Repo/include/assimp/matrix3x3.h"
#include "Repo/include/assimp/matrix4x4.h"
#include "Repo/include/assimp/mesh.h"
#include "Repo/include/assimp/postprocess.h"
#include "Repo/include/assimp/quaternion.h"
#include "Repo/include/assimp/scene.h"
#include "Repo/include/assimp/metadata.h"
#include "Repo/include/assimp/texture.h"
#include "Repo/include/assimp/types.h"
#include "Repo/include/assimp/vector2.h"
#include "Repo/include/assimp/vector3.h"
#include "Repo/include/assimp/version.h"
#include "Repo/include/assimp/cimport.h"
#include "Repo/include/assimp/importerdesc.h"
#include "Repo/include/assimp/Importer.hpp"
#include "Repo/include/assimp/DefaultLogger.hpp"
#include "Repo/include/assimp/ProgressHandler.hpp"
#include "Repo/include/assimp/IOStream.hpp"
#include "Repo/include/assimp/IOSystem.hpp"
#include "Repo/include/assimp/Logger.hpp"
#include "Repo/include/assimp/LogStream.hpp"
#include "Repo/include/assimp/NullLogger.hpp"
#include "Repo/include/assimp/cexport.h"
#include "Repo/include/assimp/Exporter.hpp"
// Logging
#include "Repo/code/FileLogStream.h"
#include "Repo/code/StdOStreamLogStream.h"
// Common
#include "Repo/code/fast_atof.h"
#include "Repo/code/qnan.h"
#include "Repo/code/BaseImporter.h"
#include "Repo/code/BaseProcess.h"
#include "Repo/code/Importer.h"
#include "Repo/code/ScenePrivate.h"
#include "Repo/code/ByteSwapper.h"
#include "Repo/code/DefaultProgressHandler.h"
#include "Repo/code/DefaultIOStream.h"
#include "Repo/code/DefaultIOSystem.h"
#include "Repo/code/CInterfaceIOWrapper.h"
#include "Repo/code/Hash.h"
#include "Repo/code/IFF.h"
#include "Repo/code/MemoryIOWrapper.h"
#include "Repo/code/ParsingUtils.h"
#include "Repo/code/StreamReader.h"
#include "Repo/code/StreamWriter.h"
#include "Repo/code/StringComparison.h"
#include "Repo/code/StringUtils.h"
#include "Repo/code/SGSpatialSort.h"
#include "Repo/code/VertexTriangleAdjacency.h"
#include "Repo/code/GenericProperty.h"
#include "Repo/code/SpatialSort.h"
#include "Repo/code/SceneCombiner.h"
#include "Repo/code/ScenePreprocessor.h"
#include "Repo/code/SkeletonMeshBuilder.h"
#include "Repo/code/SplitByBoneCountProcess.h"
#include "Repo/code/SmoothingGroups.h"
#include "Repo/code/StandardShapes.h"
#include "Repo/code/TargetAnimation.h"
#include "Repo/code/RemoveComments.h"
#include "Repo/code/Subdivision.h"
#include "Repo/code/Vertex.h"
#include "Repo/code/LineSplitter.h"
#include "Repo/code/TinyFormatter.h"
#include "Repo/code/Profiler.h"
#include "Repo/code/LogAux.h"
// ConvertUTF
#include "Repo/contrib/ConvertUTF/ConvertUTF.h"
// Clipper
#include "Repo/contrib/clipper/clipper.hpp"
#endif
