################################################################################
# Generated using Joshua T. Fisher's 'CMake Builder'.
# Link: https://github.com/playmer/CmakeBuilder 
################################################################################
target_sources(Widget
  PRIVATE
    ${CMAKE_CURRENT_LIST_DIR}/Button.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Button.hpp
    ${CMAKE_CURRENT_LIST_DIR}/CheckBox.cpp
    ${CMAKE_CURRENT_LIST_DIR}/CheckBox.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Command.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Command.hpp
    ${CMAKE_CURRENT_LIST_DIR}/CommandBinding.hpp
    ${CMAKE_CURRENT_LIST_DIR}/CommandBinding.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Composite.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Composite.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Constants.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Constants.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ContextMenu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ContextMenu.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Controls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Controls.hpp
    ${CMAKE_CURRENT_LIST_DIR}/EditText.cpp
    ${CMAKE_CURRENT_LIST_DIR}/EditText.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Events.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Events.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ImageWidget.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ImageWidget.hpp
    ${CMAKE_CURRENT_LIST_DIR}/LabeledTextBox.cpp
    ${CMAKE_CURRENT_LIST_DIR}/LabeledTextBox.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Layout.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Layout.hpp
    ${CMAKE_CURRENT_LIST_DIR}/LayoutProxy.cpp
    ${CMAKE_CURRENT_LIST_DIR}/LayoutProxy.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ListControls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ListControls.hpp
    ${CMAKE_CURRENT_LIST_DIR}/MainWindow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/MainWindow.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Manipulator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Manipulator.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Modal.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Modal.hpp
    ${CMAKE_CURRENT_LIST_DIR}/MultiDock.cpp
    ${CMAKE_CURRENT_LIST_DIR}/MultiDock.hpp
    ${CMAKE_CURRENT_LIST_DIR}/MultiManager.cpp
    ${CMAKE_CURRENT_LIST_DIR}/MultiManager.hpp
    ${CMAKE_CURRENT_LIST_DIR}/PopUp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PopUp.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Precompiled.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Precompiled.hpp
    ${CMAKE_CURRENT_LIST_DIR}/RootWidget.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RootWidget.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ScrollArea.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ScrollArea.hpp
    ${CMAKE_CURRENT_LIST_DIR}/SearchView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/SearchView.hpp
    ${CMAKE_CURRENT_LIST_DIR}/SelectorButton.cpp
    ${CMAKE_CURRENT_LIST_DIR}/SelectorButton.hpp
    ${CMAKE_CURRENT_LIST_DIR}/SimpleAnimation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/SimpleAnimation.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Slider.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Slider.hpp
    ${CMAKE_CURRENT_LIST_DIR}/TagWidgets.cpp
    ${CMAKE_CURRENT_LIST_DIR}/TagWidgets.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Text.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Text.hpp
    ${CMAKE_CURRENT_LIST_DIR}/TextBox.cpp
    ${CMAKE_CURRENT_LIST_DIR}/TextBox.hpp
    ${CMAKE_CURRENT_LIST_DIR}/TextureView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/TextureView.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Toolbar.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Toolbar.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ToolTip.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ToolTip.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Utility.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Viewport.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Viewport.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Widget.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Widget.hpp
    ${CMAKE_CURRENT_LIST_DIR}/WidgetManager.cpp
    ${CMAKE_CURRENT_LIST_DIR}/WidgetManager.hpp
    ${CMAKE_CURRENT_LIST_DIR}/WidgetMath.cpp
    ${CMAKE_CURRENT_LIST_DIR}/WidgetMath.hpp
    ${CMAKE_CURRENT_LIST_DIR}/WidgetStandard.cpp
    ${CMAKE_CURRENT_LIST_DIR}/WidgetStandard.hpp
    ${CMAKE_CURRENT_LIST_DIR}/WidgetTest.cpp
    ${CMAKE_CURRENT_LIST_DIR}/WidgetTest.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Window.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Window.hpp
)
