################################################################################
# Generated using Joshua T. Fisher's 'CMake Builder'.
# Link: https://github.com/playmer/CmakeBuilder 
################################################################################
target_sources(ZilchShaders
  PRIVATE
    ${CMAKE_CURRENT_LIST_DIR}/CodeRangeMapping.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Compositor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/GenericTranslation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/GlslTranslation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/GlslTranslator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/HlslTranslator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/LibraryTranslationHelpers.cpp
    ${CMAKE_CURRENT_LIST_DIR}/LibraryTranslator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Precompiled.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ShaderAttributes.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ShaderCodeBuilder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ShaderErrors.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ShaderIntrinsicTypes.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ShaderLibrary.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ShaderProject.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ShaderType.cpp
    ${CMAKE_CURRENT_LIST_DIR}/SimpleZilchShaderGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Translator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/TranslatorContext.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ZilchShaderSettingsLibrary.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ZilchShaderSharedSettings.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ZilchShadersStandard.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ZilchTypeCollector.cpp
#  PUBLIC
    ${CMAKE_CURRENT_LIST_DIR}/BaseShaderTranslator.hpp
    ${CMAKE_CURRENT_LIST_DIR}/CodeRangeMapping.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Compositor.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ForwardDeclarations.hpp
    ${CMAKE_CURRENT_LIST_DIR}/GenericTranslation.hpp
    ${CMAKE_CURRENT_LIST_DIR}/GlslTranslation.hpp
    ${CMAKE_CURRENT_LIST_DIR}/GlslTranslator.hpp
    ${CMAKE_CURRENT_LIST_DIR}/HlslTranslator.hpp
    ${CMAKE_CURRENT_LIST_DIR}/LibraryTranslationHelpers.hpp
    ${CMAKE_CURRENT_LIST_DIR}/LibraryTranslator.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Precompiled.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ShaderAttributes.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ShaderCodeBuilder.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ShaderErrors.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ShaderIntrinsicTypes.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ShaderLibrary.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ShaderProject.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ShaderType.hpp
    ${CMAKE_CURRENT_LIST_DIR}/SimpleZilchShaderGenerator.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Translator.hpp
    ${CMAKE_CURRENT_LIST_DIR}/TranslatorContext.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ZilchShaderSettingsLibrary.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ZilchShaderSharedSettings.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ZilchShadersStandard.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ZilchTypeCollector.hpp
)
